### ISSUE TITLE
String interpolator for constructing processes

### ISSUE THREAD

**Issue by szymon-rd** [com-lihaoyi/os-lib#188] opened 2023-07-07 15:19 UTC
We could improve usability by introducing a string interpolator as an alternative to the `os.proc` function. For example,
```scala
os.proc("curl", "-L" , "https://git.io/fpfTs")
```
Could be replaceable by:
```scala
sh"curl -L https://git.io/fpfTs"
```
We could introduce interpolation that would take care of escaping and validate the strings at compile time.

**Comment by lefou** [comment] 2023-07-08 10:44
* Duplicate of https://github.com/com-lihaoyi/os-lib/issues/46

**Closed by lefou** 2023-07-08 10:44 UTC
