### ISSUE TITLE
Ammonite failing to start on arch-linux (installed through AUR)

### ISSUE THREAD

**Issue by drewboardman** [com-lihaoyi/os-lib#49] opened 2020-12-01 16:19 UTC
```
drew@pizza ~/bin $ amm
Loading...
Exception in thread "main" os.PathError$InvalidSegment: [] is not a valid path segment. OS-Lib does not allow empty path segments If you are dealing with path-strings coming from external sources, use the Path(...) or RelPath(...) constructor calls to convert them.
        at os.BasePath$.fail$1(Path.scala:120)
        at os.BasePath$.checkSegment(Path.scala:137)
        at os.PathChunk$StringPathChunk.<init>(Path.scala:21)
        at os.PathChunk$.StringPathChunk(Path.scala:20)
        at ammonite.runtime.Storage$Folder.<init>(Storage.scala:189)
        at ammonite.MainRunner.initMain(Main.scala:452)
        at ammonite.MainRunner.watchLoop(Main.scala:396)
        at ammonite.MainRunner.runRepl(Main.scala:415)
        at ammonite.Main$.main0(Main.scala:321)
        at ammonite.Main$.main(Main.scala:270)
        at ammonite.Main.main(Main.scala)
```

OS-Lib is failing when starting ammonite with `amm`.

**Comment by DrPhil** [comment] 2021-01-07 13:03
This is not just for installations through the AUR. The [official package](https://archlinux.org/packages/community/any/ammonite/) in the Arch repository has the same issue. I can confirm that it was working in version 2.3.6 but is broken in 2.3.7.

I've not built from source to verify if the issue is upstream, but the arch build steps looks sane from a quick check.

<details>
<summary>Bisect on published version</summary>

```
❯ pacman -Q ammonite
ammonite 2.3.7-1

❯ amm
Loading...
Exception in thread "main" os.PathError$InvalidSegment: [] is not a valid path segment. OS-Lib does not allow empty path segments If you are dealing with path-strings coming from external sources, use the Path(...) or RelPath(...) constructor calls to convert them. 
	at os.BasePath$.fail$1(Path.scala:120)
	at os.BasePath$.checkSegment(Path.scala:137)
	at os.PathChunk$StringPathChunk.<init>(Path.scala:21)
	at os.PathChunk$.StringPathChunk(Path.scala:20)
	at ammonite.runtime.Storage$Folder.<init>(Storage.scala:189)
	at ammonite.MainRunner.initMain(Main.scala:452)
	at ammonite.MainRunner.watchLoop(Main.scala:396)
	at ammonite.MainRunner.runRepl(Main.scala:415)
	at ammonite.Main$.main0(Main.scala:321)
	at ammonite.Main$.main(Main.scala:270)
	at ammonite.Main.main(Main.scala)

❯ sudo env DOWNGRADE_FROM_ALA=1 downgrade ammonite

Downgrading from A.L.A. is disabled on the stable branch. To override this behavior, set DOWNGRADE_FROM_ALA to 1 .
See https://wiki.manjaro.org/index.php?title=Using_Downgrade  for more details.

Available packages:

    1)  ammonite    2.1.2  1  any  (remote)
    2)  ammonite    2.1.2  2  any  (remote)
    3)  ammonite    2.1.3  1  any  (remote)
    4)  ammonite    2.1.4  1  any  (remote)
-   5)  ammonite    2.2.0  1  any  (remote)
-   6)  ammonite    2.2.0  1  any  (local)
-   7)  ammonite    2.3.0  1  any  (remote)
-   8)  ammonite    2.3.0  1  any  (local)
    9)  ammonite    2.3.1  1  any  (remote)
   10)  ammonite    2.3.2  1  any  (remote)
-  11)  ammonite    2.3.3  1  any  (remote)
-  12)  ammonite    2.3.3  1  any  (local)
   13)  ammonite    2.3.4  1  any  (remote)
-  14)  ammonite    2.3.5  1  any  (remote)
-  15)  ammonite    2.3.5  1  any  (local)
   16)  ammonite    2.3.6  1  any  (remote)
   17)  ammonite    2.3.6  1  any  (local)
+  18)  ammonite    2.3.7  1  any  (remote)
+  19)  ammonite    2.3.7  1  any  (local)
-  20)  ammonite    2.3.8  1  any  (remote)
-  21)  ammonite    2.3.8  1  any  (local)

select a package by number: 17
loading packages...
warning: downgrading package ammonite (2.3.7-1 => 2.3.6-1)
resolving dependencies...
looking for conflicting packages...

Packages (1) ammonite-2.3.6-1

Total Installed Size:  44,26 MiB
Net Upgrade Size:       0,00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                [############################################] 100%
(1/1) checking package integrity                                              [############################################] 100%
(1/1) loading package files                                                   [############################################] 100%
(1/1) checking for file conflicts                                             [############################################] 100%
(1/1) checking available disk space                                           [############################################] 100%
:: Processing package changes...
(1/1) downgrading ammonite                                                    [############################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
add ammonite to IgnorePkg? [y/N] n


❯ amm
Loading...
Welcome to the Ammonite Repl 2.3.6 (Scala 2.13.2 Java 14.0.2)
@  
```

</details>

**Comment by DrPhil** [comment] 2021-01-07 14:40
This issue is probably a duplicate of https://github.com/lihaoyi/Ammonite/issues/1129 which is most likely a problem with packaging in Arch Linux. See this issue instead: https://bugs.archlinux.org/task/69241

**Closed** 2021-12-10 07:35 UTC
